[project]
name = "Reelio"
version = "0.1.0"
description = "A tool that extracts movies, music, books, and related people mentioned in social media content and enriches them with metadata and links to relevant platforms."
readme = "README.md"
authors = [
    { name = "Thinh" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.141.1",
]

[project.scripts]
reelio = "reelio:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
